### ISSUE TITLE
question about mutmap plot

### ISSUE THREAD

**Issue by xizhesun** [YuSugihara/MutMap#12]
Dear Yu,

I use the mutmap v2.3.3 with snpeff. The mutmap_plot were showed in the attached file. The the "red cross (❌)" made me confused.  I didn't find any information from the readme. I thought it should be from the snpeff analysis. The plot will have no red cross if I run mutmap without the snpeff. But I could not link the snpeff analysis data with the red cross. Please update more explanation for the plot.

This pipeline helps me a lot. Many thanks to the developers.

All best,
Xizhe

<img width="1098" alt="Snipaste_2022-05-05_21-07-55" src="https://user-images.githubusercontent.com/4266961/166929494-01e3017a-1a18-47ee-8d9b-38df6608ddd2.png">

**Comment by YuSugihara** [comment]
Sorry for very late reply.
"Red cross" represents INDEL.

**Comment by xizhesun** [comment]
OK, I got it. Thank you for the reply!
