### ISSUE TITLE
MutPlot error in get_significant_contigs

### ISSUE THREAD

**Issue by gtmvish** [YuSugihara/MutMap#19]
I am getting following error during mutmap analysis at the stage of mutplot.
version of mutmap = 2.3.4

`File "/media/gtmvish/base/miniforge/envs/mut_p3.10/lib/python3.10/site-packages/mutmap/plot.py", line 70, in get_significant_contigs
    significant_windows = sliding_window[abs(sliding_window['mean_p95']) <= \
TypeError: bad operand type for abs(): 'SeriesGroupBy'`

**Comment by YuSugihara** [comment]
Thank you very much for reporting this issue.
This was actually a bug and fixed since v2.3.6.

**Comment by gtmvish** [comment]
Apologies for late response. Thankyou for checking and responding. I will try the updated version.
