### ISSUE TITLE
bcftools mpileup Error !!

### ISSUE THREAD

**Issue by Elakhdar** [YuSugihara/MutMap#2]
after starting to call variants, I found this error even through using fastq or bam files
 
-r IRGSP-1.0_genome.fasta \
-c cultivar.bam \
-b bulk.bam \
-n 24 \
-o result

[MutMap:2020-08-08 21:10:53] start to run MutMap.
[MutMap:2020-08-08 21:10:53] maximum number of threads which you can use is up to 12.
[MutMap:2020-08-08 21:10:53] start to index reference fasta.
[MutMap:2020-08-08 21:14:41] indexing of reference successfully finished.
[MutMap:2020-08-08 21:14:41] start to filter reads.
[MutMap:2020-08-08 21:34:36] filtering process successfully finished.
[MutMap:2020-08-08 21:34:36] start to merge BAMs.
[MutMap:2020-08-08 21:46:14] merging process successfully finished.
[MutMap:2020-08-08 21:46:14] start to call variants.
[MutMap:2020-08-08 21:46:16] !!ERROR!! bcftools mpileup -a AD,ADF,ADR -B -q 40 -Q 18 -C 50 -O u -r chr03 -f result/10_ref/IRGSP-1.0_genome.fasta result/20_bam/cultivar.filt.bam result/20_bam/bulk.filt.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o result/30_vcf/mutmap.chr03.vcf.gz >> result/log/bcftools.chr03.log 2>&1
[MutMap:2020-08-08 21:46:16] !!ERROR!! bcftools mpileup -a AD,ADF,ADR -B -q 40 -Q 18 -C 50 -O u -r chr01 -f result/10_ref/IRGSP-1.0_genome.fasta result/20_bam/cultivar.filt.bam result/20_bam/bulk.filt.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o result/30_vcf/mutmap.chr01.vcf.gz >> result/log/bcftools.chr01.log 2>&1

please check below:

[MutMap:2020-08-08 21:46:16] !!ERROR!! bcftools mpileup -a AD,ADF,ADR -B -q 40 -Q 18 -C 50 -O u -r chr05 -f result/10_ref/IRGSP-1.0_genome.fasta result/20_bam/cultivar.filt.bam result/20_bam/bulk.filt.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o result/30_vcf/mutmap.chr05.vcf.gz >> result/log/bcftools.chr05.log 2>&1
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/...../opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))

**Comment by YuSugihara** [comment]
Hello Elakhdar,



sorry for my late response.

Please check whether this problem came from MutMap or your environment using the test datasets.
The test datasets were deposited on the Github main page of MutMap .
After entering the directory of test datasets, you can copy and run the command in mutmap.sh .

If you will not face the same problem at that time, 
that problem is probably specific to your environment.
Then, please try the MutMap again.

If you cannot solve this problem,
please ask me.
Maybe, I can help you.



Best regards,
Yu Sugihara

**Comment by Elakhdar** [comment]
YuSugihara, thank you very much.
I got the same error, in that case it might be because of my environment. 


test % mutmap -o test \
       -n 20 \
       -w 100 \
       -s 20 \
       -r mutmap_ref.fasta \
       -c mutmap_cultivar.1.fastq.gz,mutmap_cultivar.2.fastq.gz \
       -b mutmap_bulk.1.fastq.gz,mutmap_bulk.2.fastq.gz
[MutMap:2020-08-21 15:01:57] start to run MutMap.
[MutMap:2020-08-21 15:01:57] maximum number of threads which you can use is up to 12.
[MutMap:2020-08-21 15:01:57] start to index reference fasta.
[MutMap:2020-08-21 15:01:58] indexing of reference successfully finished.
[MutMap:2020-08-21 15:01:58] start to align reads of cultivar.0000 by BWA.
[MutMap:2020-08-21 15:02:09] alignment cultivar.0000 successfully finished.
[MutMap:2020-08-21 15:02:09] start to align reads of bulk.0000 by BWA.
[MutMap:2020-08-21 15:02:20] alignment bulk.0000 successfully finished.
[MutMap:2020-08-21 15:02:20] start to filter reads.
[MutMap:2020-08-21 15:02:36] filtering process successfully finished.
[MutMap:2020-08-21 15:02:36] start to merge BAMs.
[MutMap:2020-08-21 15:02:43] merging process successfully finished.
[MutMap:2020-08-21 15:02:43] start to call variants.
[MutMap:2020-08-21 15:02:43] !!ERROR!! bcftools mpileup -a AD,ADF,ADR -B -q 40 -Q 18 -C 50 -O u -r test_reference -f test/10_ref/mutmap_ref.fasta test/20_bam/cultivar.filt.bam test/20_bam/bulk.filt.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o test/30_vcf/mutmap.test_reference.vcf.gz >> test/log/bcftools.test_reference.log 2>&1

please check below:

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/aaa/MutMap/mutmap/mpileup.py", line 143, in mpileup
    check=True)
  File "/Users/aaa/opt/anaconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'bcftools mpileup -a AD,ADF,ADR -B -q 40 -Q 18 -C 50 -O u -r test_reference -f test/10_ref/mutmap_ref.fasta test/20_bam/cultivar.filt.bam test/20_bam/bulk.filt.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o test/30_vcf/mutmap.test_reference.vcf.gz >> test/log/bcftools.test_reference.log 2>&1' returned non-zero exit status 134.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaa/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/aaaaa/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/aaaa/MutMap/mutmap/mpileup.py", line 145, in mpileup
    call_log(self.out, 'bcftools', cmd1)
  File "/Users/aaaaa/MutMap/mutmap/utils.py", line 19, in call_log
    with open('{}/log/{}.log'.format(out_dir, name)) as log:
FileNotFoundError: [Errno 2] No such file or directory: 'test/log/bcftools.log'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/aaaaaar/opt/anaconda3/bin/mutmap", line 33, in <module>
    sys.exit(load_entry_point('mutmap', 'console_scripts', 'mutmap')())
  File "/Users/aaaaaar/MutMap/mutmap/mutmap.py", line 152, in main
    MutMap(args).run()
  File "/Users/ammarelakhdar/MutMap/mutmap/mutmap.py", line 147, in run
    self.mpileup()
  File "/Users/aaaaaa/MutMap/mutmap/mutmap.py", line 107, in mpileup
    mp.run()
  File "/Users/aaaaa/MutMap/mutmap/mpileup.py", line 228, in run
    p.map(self.mpileup, chr_names)
  File "/Users/aaaaaa/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/aaaaaa/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'test/log/bcftools.log'

**Comment by YuSugihara** [comment]
Ok.

At a first step, please check whether BCFtools could be installed properly in your environment by "bcftools --help" command line.

If the installation of BCFtools was failed, you can install BCFtools via bioconda, independently.

**Comment by Elakhdar** [comment]
I solved this issue as the following:
1.	brew update    
2.	brew install openssl    
3.	ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/    
4.	ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
5.	conda update –all
6.	conda install -c bioconda bcftools

% bcftools --help

Program: bcftools (Tools for variant calling and manipulating VCFs and BCFs)
License: GNU GPLv3+, due to use of the GNU Scientific Library
Version: 1.10.2 (using htslib 1.10.2)

Usage:   bcftools [--version|--version-only] [--help] <command> <argument>

Commands:

 -- Indexing
    index        index VCF/BCF files

 -- VCF/BCF manipulation
    annotate     annotate and edit VCF/BCF files
    concat       concatenate VCF/BCF files from the same set of samples
    convert      convert VCF/BCF files to different formats and back
    isec         intersections of VCF/BCF files
    merge        merge VCF/BCF files files from non-overlapping sample sets
    norm         left-align and normalize indels
    plugin       user-defined plugins
    query        transform VCF/BCF into user-defined formats
    reheader     modify VCF/BCF header, change sample names
    sort         sort VCF/BCF file
    view         VCF/BCF conversion, view, subset and filter VCF/BCF files

 -- VCF/BCF analysis
    call         SNP/indel calling
    consensus    create consensus sequence by applying VCF variants
    cnv          HMM CNV calling
    csq          call variation consequences
    filter       filter VCF/BCF files using fixed thresholds
    gtcheck      check sample concordance, detect sample swaps and contamination
    mpileup      multi-way pileup producing genotype likelihoods
    polysomy     detect number of chromosomal copies
    roh          identify runs of autozygosity (HMM)
    stats        produce VCF/BCF stats

 Most commands accept VCF, bgzipped VCF, and BCF with the file type detected
 automatically even when streaming from a pipe. Indexed VCF and BCF will work
 in all situations. Un-indexed VCF and BCF and streams will work in most but
 not all situations.

**Comment by YuSugihara** [comment]
I am happy that you solved the problem, 
and thank you for your reporting how you solved the problem.
This report might be helpful for others.


Thank you
