### ISSUE TITLE
ERROR: Could not load index.

### ISSUE THREAD

**Issue by xujiming-zju** [YuSugihara/MutMap#6]
I use mutmap to mapping gene from begining.  

when calling variants, the following error was generated :
bcftools concat -a -o z mutmap.vcf.gz mutmap.*.vcf.gz >> log/bcftools.log 2>&1
Please check below ：
Failed to open 30_vcf/mutmap.AAAA02040040.1.vcf.gz : could not load index .

Any ideas what I might be missing or overlooking?

**Comment by YuSugihara** [comment]
Can you find the index file of 30_vcf/mutmap.AAAA02040040.1.vcf.gz?

If no index file, you can create it by "tabix 30_vcf/mutmap.AAAA02040040.1.vcf.gz".
After that, please try the error command, 
bcftools concat -a -o z mutmap.vcf.gz mutmap.*.vcf.gz >> log/bcftools.log 2>&1 
in a proper directory.

Once you get VCF file, you can start from MutPlot.

Good luck
