### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by harish0201** [YuSugihara/MutMap#9]
Hi!

Say for example that I have parental lines- 2 samples and a bulk sequenced the progenies, 2 datasets that I know are phenotypically different (based on observations). Is there a way that I can apply MutMap to this situation?

Any suggestions would be really great!

Thanks!

**Comment by YuSugihara** [comment]
I'm sorry for the late response.
This sounds like a role of QTL-seq, but you need the whole-genome sequence of parental cultivar.
